CC=g++ 

LIBS=
LIBS_INC=../framework/ .

TSK=tcpacceptor.tsk
SRC=lz_tcpacceptor.t.cc lz_tcpexception.cc lz_tcpstream.cc lz_tcpacceptor.cc 

PTHREAD_ENABLED=#-pthread

CPPFLAGS=$(LIBS_INC:%=-I%) $(LIBS:%=-L%) -g -std=c++11 $(PTHREAD_ENABLED)

all:
	$(CC) $(CPPFLAGS) -o $(TSK) $(SRC)

clean:
	rm -f *.o $(TSK)
